import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import StoreProvider from "./Providers/StoreProvider";
import QueryProvider from "./Providers/QueryProvider";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="scroll-smooth">
        <QueryProvider>
       <StoreProvider>
        <Navbar></Navbar>
        <div className="min-h-[calc(100vh-450px)]"> 
        {children}
        </div>
        <Footer></Footer>
        <Toaster  />
        </StoreProvider>
       </QueryProvider>
        </div>
       
        </body>
    </html>
  );
}
